version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=logistics-api
      - POSTGRES_PASSWORD=logistics123
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres/data
  app:
    container_name: logistics-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=8000
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_DATABASE=logistics-api
      - DB_PASSWORD=logistics123
      - JWT_SECRET=secret
    depends_on:
      - db
volumes:
  db: 
